blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('post-list', views.post_list, name='post-list'),
    path('post/<int:pk>/<str:slug>/', views.post_detail, name='post-detail'),
    path('post/edit/<int:pk>/', views.post_edit, name='post-edit'),
    path('post/delete/<int:pk>/', views.post_delete, name='post-delete'),
    path('post/favourite_post/<int:pk>/', views.favourite_post, name='favourite-post'),
    path('post/create', views.post_create, name='post-create'),
    path('like/', views.like_post, name='like-post'),
    path('favourites/', views.post_favourite_list, name='post-favourite-list'),
]

dev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from pages import views
from blog import views
from accounts import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify

# Create your models here.
class  PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    objects = models.Manager()  #default Manager
    published = PublishedManager() #custom Model Manager

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    restrict_comment = models.BooleanField(default=False)
    favourite = models.ManyToManyField(User, related_name='favourite', blank=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('post-detail', args=[self.id, self.slug])

@receiver(pre_save, sender=Post)
def pre_save_slug(sender, **kwargs):
    slug = slugify(kwargs['instance'].title)
    kwargs['instance'].slug = slug

class Images(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

    def __str__(self):
        return self.post.title + 'Image'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.ForeignKey('Comment', on_delete=models.CASCADE, null=True, related_name='replies')
    content = models.TextField(max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}-{}'.format(self.post.title, str(self.user.username))

blog/forms.py
from django import forms
from .models import *

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'body',
            'status',
            'restrict_comment',
        ]



class PostEditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'body',
            'status',
            'restrict_comment',
        ]


class CommentForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Text goes here!!!', 'rows':'4', 'cols': '50'}))
    class Meta:
        model = Comment
        fields = ('content',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
from django.db.models import Q
from django.forms import modelformset_factory
from django.views.generic import View
from django.contrib import messages

from .models import *
from .forms import *

# Create your views here.
@login_required
def post_list(request):
    post_list = Post.published.all().order_by('-id')
    query = request.GET.get('q')
    if query:
        post_list = Post.published.filter(
            Q(title__icontains=query) |
            Q(author__username=query) |
            Q(body__icontains=query)
        )

    paginator = Paginator(post_list, 6)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if page is None:
        start_index = 0
        end_index = 7
    else:
        (start_index, end_index) = proper_pagination(posts, index=5)

    page_range = list(paginator.page_range)[start_index:end_index]

    context = {
        'posts': posts,
        'page_range': page_range,
    }
    return render(request, 'blog/post_list.html', context)



def proper_pagination(posts, index):
    start_index = 0
    end_index = 7
    if posts.number > index:
        start_index = posts.number - index
        end_index = start_index + end_index
    return (start_index, end_index)



@login_required
def post_detail(request, pk, slug):
    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=post, reply=None).order_by('-id')
    is_liked = False
    is_favourite = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True

    if post.favourite.filter(id=request.user.id).exists():
        is_favourite = True

    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('content')
            reply_id = request.POST.get('comment_id')
            comment_qs = None
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)
            comment = Comment.objects.create(post=post, user=request.user, content=content, reply=comment_qs)
            comment.save()
            # return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form = CommentForm()

    context = {
        'post': post,
        'is_liked': is_liked,
        'is_favourite': is_favourite,
        'total_likes': post.total_likes(),
        'comments': comments,
        'comment_form': comment_form,
    }
    if request.is_ajax():
        html = render_to_string('blog/_comments.html', context, request=request)
        return JsonResponse({'form': html})

    return render(request, 'blog/post_detail.html', context)


def post_favourite_list(request):
    user = request.user
    favourite_posts = user.favourite.all()
    context = {
    'favourite_posts': favourite_posts,
    }
    return render(request, 'blog/post_favourite_list.html', context)

def favourite_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.favourite.filter(id=request.user.id).exists():
        post.favourite.remove(request.user)
    else:
        post.favourite.add(request.user)
    return HttpResponseRedirect(post.get_absolute_url())


def like_post(request):
    # post = get_object_or_404(Post, id=request.POST.get('post_id'))
    post = get_object_or_404(Post, id=request.POST.get('id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True

    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
    }
    if request.is_ajax():
        html = render_to_string('blog/like_section.html', context, request=request)
        return JsonResponse({'form': html})



@login_required
def post_create(request):
    ImageFormset = modelformset_factory(Images, fields=('image',), extra=4)
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            print(formset.cleaned_data)

            for f in formset:
                print(f.cleaned_data)
                try:
                    photo = Images(post=post, image=f.cleaned_data.get('image'))
                    photo.save()
                except Exception as e:
                    break
            messages.success(request, "Post has been successfully created")
            return redirect('post-list')

    else:
        form = PostCreateForm()
        formset = ImageFormset(queryset = Images.objects.none())
    context = {
        'form': form,
        'formset': formset
    }
    return render(request, 'blog/post_create.html', context)



@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    ImageFormset = modelformset_factory(Images, fields=('image',), extra=4, max_num=4)
    if post.author != request.user:
        raise Http404()
    if request.method == 'POST':
        form = PostEditForm(request.POST or None, instance=post)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            form.save()
            print(formset.cleaned_data)
            data = Images.objects.filter(post=post)

            for index, f in enumerate(formset):
                if f.cleaned_data:
                    if f.cleaned_data['id'] is None:
                        photo = Images(post=post, image=f.cleaned_data.get('image'))
                        photo.save()
                    elif f.cleaned_data['image'] is False:
                        photo = Images.objects.get(id=request.POST.get('form-' + str(index) + '-id'))
                        photo.delete()
                    else:
                        photo = Images(post=post, image=f.cleaned_data.get('image'))
                        d = Images.objects.get(id=data[index].id)
                        d.image = photo.image
                        d.save()

            messages.success(request, "{} has been successfully updated".format(post.title))
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        form = PostEditForm(instance=post)
        formset = ImageFormset(queryset=Images.objects.filter(post=post))

    context = {
        'form': form,
        'post': post,
        'formset': formset
    }
    return render(request, 'blog/post_edit.html', context)



def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user != post.author:
        raise Http404()
    post.delete()
    messages.warning(request, 'Post has been successfully deleted')
    return redirect('post-list')

templates/blog/_comments.html
          <div class="container mt-2">
            <div class="form-group row">
              <form class="comment-form" action="." method="post">
                {% csrf_token %}
                {{ comment_form.as_p }}
                {% if request.user.is_authenticated %}
                <input type="submit" class="btn btn-sm btn-outline-info" value="Comment">
                {% else %}
                <input type="submit" class="btn btn-sm btn-outline-info" value="Comment" disable>
                {% endif %}
              </form>
            </div>
          </div>

          {{comments.count }} Comment{{ comments|pluralize }}
          {% for comment in comments %}
          <blockquote class="blockquote">
             <p class="mb-0"><small>{{ comment.content}}</small></p>
             <footer class="blockquote-footer">
               <small>by <cite title="Source Title">{{ comment.user|capfirst }}</cite></small>
               <button type="button" name="button" class="reply-btn btn btn-sm btn-outline-dark ml-2">Reply</button>
             </footer>
          </blockquote>

            <div class="replied-comments container mt-2" style="display: none;">
              {% for reply in comment.replies.all %}
              <blockquote class="blockquote">
                 <p class="mb-0"><small>{{ reply.content}}</small></p>
                 <footer class="blockquote-footer">
                   <small>by <cite title="Source Title">{{ reply.user|capfirst }}</cite></small>
                 </footer>
              </blockquote>
              {% endfor %}
              <div class="form-group row">
                <form class="reply-form" action="." method="post">
                  {% csrf_token %}
                  <input type="hidden" name="comment_id" value="{{ comment.id }}">
                  {{ comment_form.as_p }}
                  {% if request.user.is_authenticated %}
                  <input type="submit" class="btn btn-sm btn-outline-info" value="Reply">
                  {% else %}
                  <input type="submit" class="btn btn-sm btn-outline-info" value="Reply" disable>
                  {% endif %}
                </form>
              </div>
            </div>
          {% endfor %}

templates/blog/like_section.html
&nbsp; {{ total_likes }} Like{{ total_likes | pluralize }}
{% if request.user.is_authenticated %}
<form class="" action="{% url 'like-post' %}" method="post">
  {% csrf_token %} 
  {% if is_liked %}
  <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-sm btn-outline-danger">Dislike</button>
  {% else %}
  <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-sm btn-outline-primary">Like</button>
  {% endif %}
</form>
{% endif %}

templates/blog/post_create.html
{% extends 'base.html' %}
{% block title%}
   Blog
{% endblock %}
{% block content %}
<div class="m-5">
  <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      {{ formset.as_table }}
      <br>
      <input type="submit" value="Create" class="btn btn-sm btn-outline-success">
  </form>
</div>
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% block title%}
   Blog
{% endblock %}
{% block content %}
    <div class="m-5">
        <h3>{{ post.title }}</h3>
        <small>Post created by: {{ post.author }}</small>
        <hr>
        <p>{{ post.body }}</p>

        <div class="row gallery">
          {% for p in post.images_set.all %}
          <div class="col-md-3">
            <img src="{{ p.image.url }}" alt="Image Not Found" class="img-thumbnail">
          </div>
          {% endfor %}
        </div>

        <div class="" id="like-section">
          {% include 'blog/like_section.html' %}
        </div>

        <div id="favourite-section">
          {% if is_favourite %}
          <a href="{% url 'favourite-post' pk=post.id %}">
            <i class="fas fa-heart fa-lg"></i>
          </a>
          {% else %}
          <a href="{% url 'favourite-post' pk=post.id %}">
            <i class="far fa-heart fa-lg"></i>
          </a>
          {% endif %}
        </div>

        {% if post.author == request.user %}
        <div class="section-1" style="float: right;">
          <a href="{% url 'post-edit' pk=post.id %}">
            <button type="button" class="btn btn-sm btn-outline-info" name="button">Edit Post</button>
          </a>

          <a href="{% url 'post-delete' pk=post.id %}" id="delete">
            <button type="button" class="btn btn-sm btn-outline-danger" name="button">Delete Post</button>
          </a>
        </div>
        {% endif %}

        <br><br>
        <hr>

        {% if not post.restrict_comment %}
        <div class="main-comment-section">
          {% include 'blog/_comments.html' %}
        </div>
        {% endif %}

    </div>
{% endblock %}

templates/blog/post_edit.html
{% extends 'base.html' %}
{% block title%}
   {{post.title}}|Rdit
{% endblock %}
{% block content %}
    <form class="m-5" action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      {{ formset.management_form }}
      {% for f in formset %}
        {{ f.as_p }}
      {% endfor %}
      <input type="submit" class="btn btn-sm btn-outline-success" value="Update">
    </form>
{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}
{% block title%}
   Blog
{% endblock %}
{% block content %}
<div class="row">
  {% for post in posts %}
  <div class="col-md-6">
    <div class="img-thumbnail w3-margin">
      <a href="{{ post.get_absolute_url }}" class="w3-text-blue w3-hover-text-teal"><b>{{ post.title }}</b></a>
      <small style="float: right;"><i>{{ post.created }}</i></small>
      <br>
      Author: <a class="w3-tag w3-round w3-small w3-green ">{{ post.author }}</a>
      <br>
      {{ post.body }}
    </div>
  </div>
  <br>
  {% empty %}
  <div class="w3-margin">
    <h3>No Posts Found having "{{ request.GET.q }}"</h3>
  </div>
  {% endfor %}

  <!--pagination-->
  <div class="w3-container m-5">
    <div class="m-5">
      <ul class="pagination">
        {% if posts.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ posts.previous_page_number }}">Previous &laquo; </a>
        </li>
        {% endif %}

        {% for p in page_range %}
        {% if posts.number == p %}
        <li class="page-item active">
          <a class="page-link" href="?page={{ p }}">{{ p }}</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if posts.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ posts.next_page_number }}">Next &raquo; </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>

</div>

{% endblock %}